### ISSUE TITLE
Update to 1.7.10 Avalanche Client

### ISSUE THREAD

**Issue by bjm3** [icculp/avalanche_subnets#1]
May wish to update to [v1.7.10](https://hub.docker.com/layers/avalanchego_subnets/pocketfoundation/avalanchego_subnets/v1.7.10/images/sha256-efa3d66416078721bc76f1682d07e4ca5457d97c93870b194796d9f88d973dfc?context=explore)

docker-compose.yml

    image: pocketfoundation/avalanchego_subnets:v1.7.10

**Comment by icculp** [comment]
hey @bjm3, thanks for the suggestion. I have been watching and waiting for updates, but did not think that the 1.7.10 image was ready or had anything new worth switching for... Looking on docker hub, the layers look pretty the same although I'd say the one tagged 1.7.10 looks a little cleaner. But both are installing go 1.18, pulling avalanchgo from master and building without checking out to a specific release, and then adding the binaries for the dfk subnet. I am waiting for them to add the swimmer network binaries before I make any changes, as that's what I've been assuming they'd do, and also I assume they'll tag that image as latest when it's ready. If not, then I'll switch the tag here. Is my thinking sound or do you have any insights?

**Comment by icculp** [comment]
Have updated to 1.7.10 via `image: pocketfoundation/avalanchego:1.7.10-subnets`
